# Este archivo configura la construcción de la documentación en Read the Docs

version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.9"

conda:
  environment: environment.yml

docs_dir: docs

sphinx:
  configuration: docs/conf.py

extra_requirements:
  - developer

output:
  format: html
