# Este archivo configura la construcción de la documentación en Read the Docs

version: 2

python:
  version: "3.9"

build:
  image: "python:3.9"
  os: "ubuntu-20.04"
  tools:
    python: "3.9"

conda:
  dependencies:
    - python=3.9
    - requests
    - matplotlib
    - wordcloud
    - fpdf
    - pip:
        - grobid-client

docs_dir: docs

sphinx:
  configuration: docs/conf.py

extra_requirements:
  - developer

output:
  format: html
