version: '3.8'

services:
  grobid:
    image: lfoppiano/grobid:0.8.1
    ports:
      - "8070:8070"
    restart: unless-stopped

  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - grobid
    environment:
      - GROBID_URL=http://grobid:8070/api/processFulltextDocument
      - GROBID_ALIVE=http://grobid:8070/api/health
    volumes:
      - ./data:/app/data